<template>
    <div>
        <h3>The Customer Page</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores quidem nulla quas, doloremque minima blanditiis odit aut illum. Laborum, mollitia. Ipsam fugiat eius iure debitis delectus quod, perferendis ad, ratione illo, cum perspiciatis! Dolorem fugit voluptas laborum, culpa nemo assumenda facilis consequuntur ut sunt laboriosam ducimus dolorum quae quisquam dolore, molestiae, sapiente alias blanditiis praesentium fuga et animi beatae. Quo, provident fugit odio praesentium fugiat voluptates? Quidem ipsam accusamus quisquam, sequi eius ipsum nostrum necessitatibus architecto exercitationem tenetur qui incidunt unde nihil maiores ut pariatur earum alias itaque magni corrupti temporibus officia libero veritatis. Cumque nulla perspiciatis repellat molestias atque!</p>
        <!-- <p>Customer Id : {{ lodedId }}</p> -->
        <button @click="navigateToHome">Go to Home</button>


        <!-- Vue Nested Route -->
        <hr>
        <router-view></router-view>
    </div>
</template>

<script>

export default {
    name: 'CustomerPage',
    // data() {
    //     return {
    //         lodedId: this.$route.params.id
    //     }
    // },
    // watch: {
    //     '$route'(to){
    //         this.lodedId= to.params.id;
    //     }
    // },
    methods: {
        navigateToHome(){
            // this.$router.push('/');

            // Route name Use kore
            this.$router.push({name: 'home'});
        }
    }
}
</script>

<style scoped>
    
</style>